# Generated by Django 4.0.4 on 2022-04-24 00:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banner', models.ImageField(upload_to='offers', verbose_name='Banner de Oferta')),
                ('init_offer', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('end_offer', models.DateTimeField(verbose_name='Fecha de Fin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
